"""
=============================================================================
test_models.py — Model Validation & Smoke-Test Suite
=============================================================================
Cosmetic Market Intelligence System
Author  : Auto-generated by Antigravity
Version : 1.0.0

Tests every trained artefact in backend/models/ and verifies end-to-end
inference for all five model families.

Usage:
    python backend/test_models.py
    python backend/test_models.py --verbose
    python backend/test_models.py --models all
    python backend/test_models.py --models similarity harmful skin sentiment forecast
=============================================================================
"""

import os
import sys
import time
import pickle
import argparse
import warnings
import traceback
from pathlib import Path
from typing import Any, Optional

import numpy as np

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# COLOUR HELPERS  (works on macOS/Linux; degrades gracefully on Windows)
# ─────────────────────────────────────────────────────────────────────────────

class C:
    """ANSI colour codes."""
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"
    GREEN   = "\033[92m"
    RED     = "\033[91m"
    YELLOW  = "\033[93m"
    CYAN    = "\033[96m"
    BLUE    = "\033[94m"
    MAGENTA = "\033[95m"
    WHITE   = "\033[97m"
    GREY    = "\033[90m"

    @staticmethod
    def ok(text: str) -> str:
        return f"{C.GREEN}{C.BOLD}✔ {text}{C.RESET}"

    @staticmethod
    def fail(text: str) -> str:
        return f"{C.RED}{C.BOLD}✘ {text}{C.RESET}"

    @staticmethod
    def warn(text: str) -> str:
        return f"{C.YELLOW}⚠  {text}{C.RESET}"

    @staticmethod
    def info(text: str) -> str:
        return f"{C.CYAN}ℹ  {text}{C.RESET}"

    @staticmethod
    def header(text: str) -> str:
        width = 68
        bar   = "═" * width
        return (
            f"\n{C.BLUE}{C.BOLD}╔{bar}╗\n"
            f"║  {text:<{width - 2}}║\n"
            f"╚{bar}╝{C.RESET}"
        )

    @staticmethod
    def sub(text: str) -> str:
        return f"{C.MAGENTA}{C.BOLD}▶ {text}{C.RESET}"

    @staticmethod
    def result(label: str, value: Any) -> str:
        return f"  {C.WHITE}{C.BOLD}{label:<28}{C.RESET}= {C.GREEN}{value}{C.RESET}"

    @staticmethod
    def kv(label: str, value: Any) -> str:
        return f"  {C.GREY}{label:<30}{C.RESET}{value}"


# ─────────────────────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────────────────────

BASE_DIR   = Path(__file__).resolve().parent         # backend/
MODELS_DIR = BASE_DIR / "models"

ARTEFACTS = {
    "tfidf_vectorizer":        MODELS_DIR / "tfidf_vectorizer.pkl",
    "cosine_similarity_matrix": MODELS_DIR / "cosine_similarity_matrix.pkl",
    "product_id_index":        MODELS_DIR / "product_id_index.pkl",
    "harmful_detector":        MODELS_DIR / "harmful_detector.pkl",
    "skin_model":              MODELS_DIR / "skin_model.pkl",
    "sentiment_model":         MODELS_DIR / "sentiment_model.pkl",
    "rf_forecast_model":       MODELS_DIR / "rf_forecast_model.pkl",
    "arima_model":             MODELS_DIR / "arima_model.pkl",
}

# ─────────────────────────────────────────────────────────────────────────────
# TEST RESULT TRACKER
# ─────────────────────────────────────────────────────────────────────────────

class TestSuite:
    """Collects and reports test outcomes."""

    def __init__(self) -> None:
        self.passed:  list[str] = []
        self.failed:  list[str] = []
        self.skipped: list[str] = []
        self._start   = time.time()

    def ok(self, name: str, detail: str = "") -> None:
        self.passed.append(name)
        suffix = f"  {C.GREY}({detail}){C.RESET}" if detail else ""
        print(C.ok(f"{name}{suffix}"))

    def fail(self, name: str, reason: str = "") -> None:
        self.failed.append(name)
        print(C.fail(f"{name}"))
        if reason:
            print(f"    {C.RED}{reason}{C.RESET}")

    def skip(self, name: str, reason: str = "") -> None:
        self.skipped.append(name)
        print(C.warn(f"SKIPPED — {name}" + (f": {reason}" if reason else "")))

    def summary(self) -> None:
        elapsed = time.time() - self._start
        total   = len(self.passed) + len(self.failed) + len(self.skipped)
        print(C.header("TEST SUMMARY"))
        print(C.kv("Total tests ran:", total))
        print(C.kv("Passed: ",  f"{C.GREEN}{C.BOLD}{len(self.passed)}{C.RESET}"))
        print(C.kv("Failed: ",  f"{C.RED}{C.BOLD}{len(self.failed)}{C.RESET}"))
        print(C.kv("Skipped:", f"{C.YELLOW}{len(self.skipped)}{C.RESET}"))
        print(C.kv("Elapsed:", f"{elapsed:.2f}s"))
        print()
        if self.failed:
            print(f"  {C.RED}{C.BOLD}Failed tests:{C.RESET}")
            for f in self.failed:
                print(f"    {C.RED}• {f}{C.RESET}")
            print()
            print(C.fail("Some tests failed. Review output above."))
        else:
            print(f"  {C.GREEN}{C.BOLD}{'All models working correctly':^64}{C.RESET}")
            print(f"  {C.GREEN}{'🎉  Pipeline validated end-to-end':^64}{C.RESET}")
        print()
        return len(self.failed) == 0


suite = TestSuite()


# ─────────────────────────────────────────────────────────────────────────────
# LOAD HELPER
# ─────────────────────────────────────────────────────────────────────────────

def load_pkl(key: str) -> Optional[Any]:
    """
    Load a pickle artefact by symbolic key.

    Parameters
    ----------
    key : Key from ARTEFACTS dict.

    Returns
    -------
    Deserialized object or None if file missing.
    """
    path = ARTEFACTS.get(key)
    if path is None:
        print(C.warn(f"Unknown artefact key: '{key}'"))
        return None
    if not path.exists():
        print(C.warn(f"File missing: {path.name}"))
        return None
    try:
        t0  = time.time()
        obj = pickle.load(open(path, "rb"))
        ms  = (time.time() - t0) * 1000
        size_kb = path.stat().st_size / 1024
        print(C.kv(f"  Loaded {path.name}:", f"{size_kb:.1f} KB  in {ms:.0f} ms"))
        return obj
    except Exception as exc:
        print(C.fail(f"Failed to load {path.name}: {exc}"))
        return None


# ─────────────────────────────────────────────────────────────────────────────
# SAMPLE DATA
# ─────────────────────────────────────────────────────────────────────────────

SAMPLE_REVIEWS = [
    "This moisturiser is absolutely incredible for my dry skin. "
    "It feels so hydrating and soothing all day long.",

    "Terrible product. Broke me out immediately and left my oily skin "
    "looking greasy and congested.",

    "Really nice serum. My sensitive skin tolerated it well and the redness "
    "has calmed down significantly after two weeks of use.",

    "Great for combination skin! Light texture, absorbs fast, and keeps "
    "my T-zone matte while hydrating my cheeks.",

    "The formula irritated my normal skin after repeated use. "
    "Not what I expected from such a well-known brand.",
]

SAMPLE_INGREDIENTS = [
    # Safe — no harmful keywords
    "Water, Glycerin, Niacinamide, Ceramide NP, Sodium Hyaluronate, "
    "Panthenol, Allantoin, Arginine, Citric Acid, Sodium Chloride",

    # Moderate — contains parabens & phenoxyethanol
    "Water, Methylparaben, Propylparaben, Phenoxyethanol, Glycerin, "
    "Tocopheryl Acetate, Dimethicone, Sodium Laureth Sulfate, Fragrance",

    # Unsafe — formaldehyde releaser, oxybenzone, SLS
    "Water, Sodium Lauryl Sulfate, Oxybenzone, DMDM Hydantoin, "
    "Quaternium-15, Formaldehyde, Phthalate, Petroleum, PEG-100 Stearate",
]

SAMPLE_FORECAST_HISTORY = [120.0, 135.0, 128.0, 145.0, 158.0, 163.0, 172.0, 180.0]


# ─────────────────────────────────────────────────────────────────────────────
# TEST 1 — TF-IDF VECTORIZER
# ─────────────────────────────────────────────────────────────────────────────

def test_tfidf() -> Optional[Any]:
    print(C.sub("TF-IDF Vectorizer"))
    vectorizer = load_pkl("tfidf_vectorizer")
    if vectorizer is None:
        suite.skip("TF-IDF loaded", "file missing")
        return None

    try:
        vocab_size    = len(vectorizer.vocabulary_)
        n_features    = len(vectorizer.get_feature_names_out())
        ngram_range   = vectorizer.ngram_range
        max_features  = vectorizer.max_features

        print(C.result("TF-IDF loaded successfully", "YES"))
        print(C.kv("  Vocabulary size:", f"{vocab_size:,}"))
        print(C.kv("  n_features:", f"{n_features:,}"))
        print(C.kv("  ngram_range:", ngram_range))
        print(C.kv("  max_features:", max_features))

        # Transform a sample text
        vec = vectorizer.transform(["water glycerin niacinamide ceramide hyaluronate"])
        print(C.kv("  Sample transform shape:", vec.shape))
        assert vec.shape[1] == n_features, "Feature dimension mismatch"

        suite.ok("TF-IDF loaded", f"vocab={vocab_size:,} features")
        return vectorizer

    except Exception as exc:
        suite.fail("TF-IDF loaded", str(exc))
        return None


# ─────────────────────────────────────────────────────────────────────────────
# TEST 2 — COSINE SIMILARITY MATRIX
# ─────────────────────────────────────────────────────────────────────────────

def test_cosine_matrix() -> None:
    print(C.sub("Cosine Similarity Matrix"))
    sim_matrix = load_pkl("cosine_similarity_matrix")
    id_map     = load_pkl("product_id_index")

    if sim_matrix is None:
        suite.skip("Cosine matrix shape", "file missing")
        return

    try:
        shape = sim_matrix.shape
        print(C.result("Cosine matrix shape", f"{shape[0]} × {shape[1]}"))
        assert shape[0] == shape[1], "Matrix must be square"

        # Pick a random product and retrieve top-5 similar
        if id_map:
            product_ids   = id_map["product_ids"]
            product_names = id_map["product_names"]

            rng       = np.random.default_rng(seed=42)
            rand_idx  = int(rng.integers(0, len(product_ids)))
            sims      = sim_matrix[rand_idx].toarray().flatten()
            top_idx   = np.argsort(sims)[::-1][1:6]

            sample_name = product_names[rand_idx]
            print(C.kv("  Random product:", f"'{sample_name}'"))
            print(C.kv("  Top-5 similar:", ""))
            for rank, i in enumerate(top_idx, 1):
                score = sims[i]
                print(f"    {C.GREY}{rank}.{C.RESET} "
                      f"{product_names[i]:<50s}  "
                      f"{C.GREEN}{score:.4f}{C.RESET}")

            print(C.result("Similar products found", f"top-5 for idx={rand_idx}"))

        suite.ok("Cosine matrix shape", f"{shape[0]}×{shape[1]} sparse matrix")

    except Exception as exc:
        suite.fail("Cosine matrix shape", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# TEST 3 — HARMFUL INGREDIENT DETECTOR
# ─────────────────────────────────────────────────────────────────────────────

def test_harmful_detector() -> None:
    print(C.sub("Harmful Ingredient Detector"))
    payload = load_pkl("harmful_detector")

    if payload is None:
        suite.skip("Harmful detector", "file missing")
        return

    try:
        keywords = payload.get("harmful_keywords", {})
        stats    = payload.get("stats", {})
        print(C.kv("  Harmful keywords loaded:", f"{len(keywords):,}"))
        if stats:
            print(C.kv("  Products scored:", f"{stats.get('n_products', '?'):,}"))
            print(C.kv("  Mean safety score:", stats.get('mean_safety', '?')))

        # Inline scoring function (mirrors train.py)
        def score(text: str):
            if not text:
                return 100.0, []
            t      = text.lower()
            found  = []
            sev    = 0
            for kw, info in keywords.items():
                if kw in t:
                    found.append(info["name"])
                    sev += info["severity"]
            return round(max(0.0, 100.0 - min(sev * 4, 100)), 1), found

        print()
        print(f"  {C.BOLD}Safety scoring — 3 sample ingredient lists:{C.RESET}")
        labels = ["Safe (clean formula)", "Moderate (parabens + SLES)", "Unsafe (formaldehyde + SLS + oxybenzone)"]
        expected_statuses = ["Safe", "Safe/Moderate", "Unsafe"]

        all_ok = True
        for label, ing_text in zip(labels, SAMPLE_INGREDIENTS):
            safety_score, found = score(ing_text)
            status = "Safe" if safety_score >= 80 else ("Moderate" if safety_score >= 50 else "Unsafe")
            colour = C.GREEN if status == "Safe" else (C.YELLOW if status == "Moderate" else C.RED)
            print(f"    {C.GREY}•{C.RESET} {label:<45s}  "
                  f"score={colour}{safety_score:5.1f}{C.RESET}  "
                  f"status={colour}{status}{C.RESET}  "
                  f"harmful={C.YELLOW}{found if found else '[]'}{C.RESET}")

        print(C.result("Harmful detector", "Functional ✔"))
        suite.ok("Harmful detector", f"{len(keywords)} keywords")

    except Exception as exc:
        suite.fail("Harmful detector", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# TEST 4 — SKIN-TYPE CLASSIFIER
# ─────────────────────────────────────────────────────────────────────────────

def test_skin_model() -> None:
    print(C.sub("Skin-Type Classifier"))
    model = load_pkl("skin_model")
    if model is None:
        suite.skip("Skin prediction", "file missing")
        return

    try:
        classes = model.classes_
        print(C.kv("  Classes:", list(classes)))

        print()
        print(f"  {C.BOLD}Skin-type predictions — {len(SAMPLE_REVIEWS)} sample reviews:{C.RESET}")
        for i, review in enumerate(SAMPLE_REVIEWS, 1):
            pred  = model.predict([review])[0]
            proba = model.predict_proba([review])[0]
            conf  = max(proba)
            bar   = "█" * int(conf * 20) + "░" * (20 - int(conf * 20))
            print(f"    {C.GREY}{i}.{C.RESET} "
                  f"{C.CYAN}{pred:<12}{C.RESET}  "
                  f"conf={C.GREEN}{conf:.3f}{C.RESET}  "
                  f"[{C.GREEN}{bar}{C.RESET}]")
            print(f"       {C.GREY}└ \"{review[:75]}…\"{C.RESET}")

        # Last prediction for the result line
        last_pred = model.predict([SAMPLE_REVIEWS[-1]])[0]
        print()
        print(C.result("Skin prediction", last_pred))
        suite.ok("Skin prediction", f"classes={list(classes)}")

    except Exception as exc:
        suite.fail("Skin prediction", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# TEST 5 — SENTIMENT MODEL
# ─────────────────────────────────────────────────────────────────────────────

def test_sentiment_model() -> None:
    print(C.sub("Sentiment Analysis Model"))
    payload = load_pkl("sentiment_model")
    if payload is None:
        suite.skip("Sentiment prediction", "file missing")
        return

    SENTIMENT_COLOURS = {
        "positive": C.GREEN,
        "neutral":  C.YELLOW,
        "negative": C.RED,
    }

    def _vader_label(compound: float) -> str:
        if compound >= 0.05:  return "positive"
        if compound <= -0.05: return "negative"
        return "neutral"

    try:
        mode = payload.get("mode", "unknown")
        print(C.kv("  Mode:", mode))

        print()
        print(f"  {C.BOLD}Sentiment predictions — {len(SAMPLE_REVIEWS)} sample reviews:{C.RESET}")

        all_preds = []
        for i, review in enumerate(SAMPLE_REVIEWS, 1):
            if mode == "classifier":
                pipeline = payload["pipeline"]
                pred     = pipeline.predict([review])[0]
                proba    = pipeline.predict_proba([review])[0]
                conf     = max(proba)
                detail   = f"conf={conf:.3f}"
            elif mode == "vader":
                analyzer = payload["analyzer"]
                scores   = analyzer.polarity_scores(review)
                pred     = _vader_label(scores["compound"])
                detail   = f"compound={scores['compound']:.4f}"
            else:
                from textblob import TextBlob
                pol  = TextBlob(review).sentiment.polarity
                pred = "positive" if pol > 0.05 else ("negative" if pol < -0.05 else "neutral")
                detail = f"polarity={pol:.4f}"

            colour = SENTIMENT_COLOURS.get(pred, C.WHITE)
            all_preds.append(pred)
            print(f"    {C.GREY}{i}.{C.RESET} "
                  f"{colour}{pred:<10}{C.RESET}  "
                  f"{C.GREY}{detail:<24}{C.RESET}  "
                  f"\"{review[:60]}…\"")

        last_pred = all_preds[-1] if all_preds else "unknown"
        print()
        print(C.result("Sentiment prediction", f"{last_pred}  (mode={mode})"))
        suite.ok("Sentiment prediction", f"mode={mode}")

    except Exception as exc:
        suite.fail("Sentiment prediction", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# TEST 6 — RANDOM FOREST DEMAND FORECASTING
# ─────────────────────────────────────────────────────────────────────────────

def test_rf_forecast() -> None:
    print(C.sub("Random Forest Demand Forecast"))
    payload = load_pkl("rf_forecast_model")
    if payload is None:
        suite.skip("RF Forecast", "file missing")
        return

    try:
        rf           = payload["model"]
        feature_cols = payload["feature_cols"]

        print(C.kv("  n_estimators:", rf.n_estimators))
        print(C.kv("  max_depth:", rf.max_depth))
        print(C.kv("  Feature columns:", feature_cols))

        # Build 7-step forecast
        import pandas as pd
        history  = list(SAMPLE_FORECAST_HISTORY)
        steps    = 7
        ref_date = pd.Timestamp("2025-09-01")
        forecast: list[float] = []

        for step in range(steps):
            future = ref_date + pd.DateOffset(weeks=step + 1)
            row = {
                "month":          future.month,
                "week_of_year":   future.isocalendar()[1],
                "quarter":        future.quarter,
                "season":         (future.quarter - 1) % 4 + 1,
                "is_holiday":     int(future.quarter == 4),
                "lag_1":          history[-1],
                "lag_2":          history[-2] if len(history) >= 2 else history[-1],
                "lag_4":          history[-4] if len(history) >= 4 else history[-1],
                "lag_8":          history[-8] if len(history) >= 8 else history[-1],
                "rolling_mean_4": float(np.mean(history[-4:])),
            }
            x    = np.array([[row[c] for c in feature_cols]])
            pred = float(max(0.0, rf.predict(x)[0]))
            forecast.append(round(pred, 2))
            history.append(pred)

        # Visualise as sparkline
        mn, mx = min(forecast), max(forecast)
        span   = mx - mn if mx != mn else 1.0
        spark  = "".join(
            ["▁▂▃▄▅▆▇█"[min(7, int(7 * (v - mn) / span))] for v in forecast]
        )

        print()
        print(f"  {C.BOLD}7-week demand forecast (starting 2025-09-01):{C.RESET}")
        for w, val in enumerate(forecast, 1):
            bar = "█" * min(40, int(val / max(forecast) * 40))
            print(f"    Week {w}:  {C.GREEN}{val:8.2f}{C.RESET}  {C.BLUE}{bar}{C.RESET}")

        print()
        print(C.kv("  Sparkline:", f"{C.CYAN}{spark}{C.RESET}"))
        print(C.kv("  Min / Max:", f"{mn:.2f} / {mx:.2f}"))
        trend = "↑ rising" if forecast[-1] > forecast[0] else ("↓ falling" if forecast[-1] < forecast[0] else "→ flat")
        print(C.kv("  Trend:", trend))
        print()
        print(C.result("Forecast",
                       f"[{', '.join(str(v) for v in forecast[:4])} …]"))
        suite.ok("RF Forecast", f"7-week  min={mn:.1f} max={mx:.1f}")

    except Exception as exc:
        suite.fail("RF Forecast", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# TEST 7 — ARIMA MODELS (optional)
# ─────────────────────────────────────────────────────────────────────────────

def test_arima() -> None:
    print(C.sub("ARIMA Demand Forecast Models"))
    payload = load_pkl("arima_model")
    if payload is None:
        suite.skip("ARIMA Forecast", "file missing — optional")
        return

    try:
        models       = payload.get("models", {})
        top_products = payload.get("top_products", [])

        print(C.kv("  Number of ARIMA models:", len(models)))
        print(C.kv("  Top products:", top_products[:5]))

        if not models:
            suite.skip("ARIMA Forecast", "no fitted models in payload")
            return

        # Forecast first available model
        pid    = list(models.keys())[0]
        fitted = models[pid]
        steps  = 6
        fc     = fitted.forecast(steps=steps)
        values = [round(max(0.0, float(v)), 2) for v in fc]

        print()
        print(f"  {C.BOLD}ARIMA 6-week forecast — product: {pid}{C.RESET}")
        for w, val in enumerate(values, 1):
            bar = "█" * min(40, int(val / max(values or [1]) * 40))
            print(f"    Week {w}:  {C.GREEN}{val:8.2f}{C.RESET}  {C.BLUE}{bar}{C.RESET}")

        print()
        print(C.result("ARIMA Forecast", f"[{', '.join(str(v) for v in values[:4])} …]"))
        suite.ok("ARIMA Forecast", f"{len(models)} model(s)  product={pid}")

    except Exception as exc:
        suite.fail("ARIMA Forecast", str(exc))
        if VERBOSE:
            traceback.print_exc()


# ─────────────────────────────────────────────────────────────────────────────
# ARTEFACT INVENTORY CHECK
# ─────────────────────────────────────────────────────────────────────────────

def check_artefact_inventory() -> None:
    print(C.sub("Artefact Inventory"))
    print(f"  {C.BOLD}{'File':<45}  {'Size':>10}  {'Status'}{C.RESET}")
    print(f"  {'─' * 70}")
    for key, path in ARTEFACTS.items():
        if path.exists():
            size_mb = path.stat().st_size / (1024 * 1024)
            size_str = f"{size_mb:.2f} MB" if size_mb >= 1 else f"{path.stat().st_size / 1024:.1f} KB"
            status = f"{C.GREEN}✔ present{C.RESET}"
        else:
            size_str = "—"
            status   = f"{C.RED}✘ missing{C.RESET}"
        print(f"  {path.name:<45}  {size_str:>10}  {status}")
    print()


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

AVAILABLE = ["similarity", "harmful", "skin", "sentiment", "forecast", "arima"]

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Smoke-test all trained ML models in backend/models/."
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=["all"],
        choices=AVAILABLE + ["all"],
        help="Which model tests to run (default: all).",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print full tracebacks on failure.",
    )
    return parser.parse_args()


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

VERBOSE = False


def main() -> None:
    global VERBOSE

    args    = parse_args()
    VERBOSE = args.verbose
    run_all = "all" in args.models
    to_run  = AVAILABLE if run_all else args.models

    print(C.header("COSMETIC ML — MODEL VALIDATION SUITE"))
    print(C.kv("  Models dir:", MODELS_DIR))
    print(C.kv("  Tests to run:", to_run))
    print(C.kv("  Python:", sys.version.split()[0]))
    print()

    # ── Inventory ────────────────────────────────────────────────────────────
    check_artefact_inventory()

    # ── Run each test ─────────────────────────────────────────────────────────
    TESTS = {
        "similarity": (test_tfidf, test_cosine_matrix),
        "harmful":    (test_harmful_detector,),
        "skin":       (test_skin_model,),
        "sentiment":  (test_sentiment_model,),
        "forecast":   (test_rf_forecast,),
        "arima":      (test_arima,),
    }

    for group in to_run:
        print(C.header(f"TEST GROUP: {group.upper()}"))
        for fn in TESTS.get(group, []):
            try:
                fn()
            except Exception as exc:
                suite.fail(fn.__name__, str(exc))
                if VERBOSE:
                    traceback.print_exc()
            print()

    # ── Summary ───────────────────────────────────────────────────────────────
    success = suite.summary()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
