"""
=============================================================================
train.py — End-to-End ML Training Pipeline for Cosmetic Market Intelligence
=============================================================================
Author  : Auto-generated by Antigravity
Created : 2026-04-08
Version : 1.0.0

Models trained:
  1. Ingredient Similarity    — TF-IDF + Cosine Similarity
  2. Harmful Ingredient Detector — Rule-based scoring engine
  3. Skin-Type Classifier     — TF-IDF + Logistic Regression
  4. Sentiment Analyzer       — VADER rule-based (with classifier fallback)
  5. Demand Forecasting       — ARIMA (per product) + RandomForestRegressor

Usage:
  python backend/train.py
  python backend/train.py --models all
  python backend/train.py --models similarity harmful skin sentiment forecast

All artefacts are saved to: backend/models/
=============================================================================
"""

import os
import sys
import time
import logging
import argparse
import warnings
from typing import Optional, Dict, List, Tuple
import pickle
import json
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────────────────────
# train.py lives in scripts/ — backend/ is one level up from project root
BASE_DIR   = Path(__file__).resolve().parent.parent / "backend"
DATA_DIR   = BASE_DIR / "data" / "cleaned"
MODELS_DIR = BASE_DIR / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

DATA_MASTER   = DATA_DIR / "master_cleaned.csv"
DATA_SALES    = DATA_DIR / "master_sales_cleaned.csv"
DATA_REVIEWS  = DATA_DIR / "master_reviews_cleaned.csv"

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING SETUP
# ─────────────────────────────────────────────────────────────────────────────

LOG_PATH = MODELS_DIR / "training_log.txt"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)-8s]  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(str(LOG_PATH), mode="w", encoding="utf-8"),
    ],
)
logger = logging.getLogger("TrainPipeline")


def log_section(title: str) -> None:
    """Print a formatted section header to the log."""
    sep = "=" * 70
    logger.info(sep)
    logger.info(f"  {title}")
    logger.info(sep)


def elapsed(start: float) -> str:
    """Return elapsed time string."""
    return f"{time.time() - start:.1f}s"


# ─────────────────────────────────────────────────────────────────────────────
# HARMFUL INGREDIENT CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

HARMFUL_KEYWORDS: Dict[str, dict] = {
    # key → (display_name, reason, severity 1-10)
    "paraben": {
        "name": "Parabens",
        "reason": "Endocrine disruptor; linked to hormonal imbalances",
        "severity": 7,
    },
    "methylparaben": {
        "name": "Methylparaben",
        "reason": "Paraben-class preservative; endocrine disruptor",
        "severity": 7,
    },
    "propylparaben": {
        "name": "Propylparaben",
        "reason": "Paraben-class preservative; endocrine disruptor",
        "severity": 7,
    },
    "butylparaben": {
        "name": "Butylparaben",
        "reason": "Paraben-class preservative; endocrine disruptor",
        "severity": 7,
    },
    "sodium lauryl sulfate": {
        "name": "Sodium Lauryl Sulfate (SLS)",
        "reason": "Skin irritant; strips natural oils",
        "severity": 5,
    },
    "sodium laureth sulfate": {
        "name": "Sodium Laureth Sulfate (SLES)",
        "reason": "Potentially contaminated with carcinogen 1,4-dioxane",
        "severity": 6,
    },
    "sls": {
        "name": "SLS",
        "reason": "Surfactant; skin and eye irritant",
        "severity": 5,
    },
    "sles": {
        "name": "SLES",
        "reason": "Surfactant; possible carcinogen contamination",
        "severity": 6,
    },
    "oxybenzone": {
        "name": "Oxybenzone",
        "reason": "Endocrine disruptor; coral reef bleaching agent",
        "severity": 8,
    },
    "phthalate": {
        "name": "Phthalates",
        "reason": "Endocrine disruptor; reproductive toxicant",
        "severity": 8,
    },
    "diethyl phthalate": {
        "name": "Diethyl Phthalate",
        "reason": "Phthalate plasticiser; reproductive toxicant",
        "severity": 8,
    },
    "formaldehyde": {
        "name": "Formaldehyde",
        "reason": "Known human carcinogen (IARC Group 1)",
        "severity": 10,
    },
    "quaternium-15": {
        "name": "Quaternium-15",
        "reason": "Formaldehyde releaser; carcinogen risk",
        "severity": 9,
    },
    "dmdm hydantoin": {
        "name": "DMDM Hydantoin",
        "reason": "Formaldehyde releaser; carcinogen risk",
        "severity": 9,
    },
    "imidazolidinyl urea": {
        "name": "Imidazolidinyl Urea",
        "reason": "Formaldehyde releaser",
        "severity": 8,
    },
    "peg": {
        "name": "PEGs (Polyethylene Glycols)",
        "reason": "Potential contamination with carcinogenic 1,4-dioxane",
        "severity": 5,
    },
    "polyethylene glycol": {
        "name": "Polyethylene Glycol",
        "reason": "PEG compound; potential carcinogen contamination",
        "severity": 5,
    },
    "petroleum": {
        "name": "Petroleum / Petrolatum",
        "reason": "Risk of polycyclic aromatic hydrocarbon (PAH) contamination",
        "severity": 5,
    },
    "mineral oil": {
        "name": "Mineral Oil",
        "reason": "Petroleum derivative; pore-clogging in high concentrations",
        "severity": 4,
    },
    "phenoxyethanol": {
        "name": "Phenoxyethanol",
        "reason": "Potential skin sensitiser; toxic to immune system at high levels",
        "severity": 4,
    },
    "triclosan": {
        "name": "Triclosan",
        "reason": "Antibiotic resistance; endocrine disruptor",
        "severity": 8,
    },
    "talc": {
        "name": "Talc",
        "reason": "Possible asbestos contamination; lung irritant",
        "severity": 6,
    },
    "hydroquinone": {
        "name": "Hydroquinone",
        "reason": "Skin bleaching agent; linked to ochronosis; restricted in EU",
        "severity": 7,
    },
    "coal tar": {
        "name": "Coal Tar",
        "reason": "Known carcinogen; restricted in many countries",
        "severity": 9,
    },
    "lead": {
        "name": "Lead",
        "reason": "Heavy metal; neurotoxicant",
        "severity": 10,
    },
    "mercury": {
        "name": "Mercury",
        "reason": "Heavy metal; neurotoxicant and nephrotoxic",
        "severity": 10,
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# HELPER UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

def save_model(obj, filename: str, description: str = "") -> None:
    """
    Serialise *obj* to MODELS_DIR/<filename> using pickle.

    Parameters
    ----------
    obj        : Any picklable Python object.
    filename   : Filename (e.g. 'tfidf_vectorizer.pkl').
    description: Human-readable description for the log.
    """
    path = MODELS_DIR / filename
    with open(path, "wb") as f:
        pickle.dump(obj, f, protocol=pickle.HIGHEST_PROTOCOL)
    size_kb = path.stat().st_size / 1024
    logger.info(f"  ✔ Saved {description or filename:40s}  →  {path.name}  ({size_kb:.1f} KB)")


def load_csv(path: Path, name: str, **kwargs) -> pd.DataFrame:
    """
    Load a CSV file with basic error handling and logging.

    Parameters
    ----------
    path  : Absolute path to the CSV.
    name  : Human-readable name for log messages.
    kwargs: Extra keyword arguments forwarded to pd.read_csv().

    Returns
    -------
    pd.DataFrame with loaded data, or empty DataFrame on failure.
    """
    logger.info(f"  Loading {name} from {path.name} …")
    if not path.exists():
        logger.error(f"  ✘ File not found: {path}")
        return pd.DataFrame()
    try:
        df = pd.read_csv(path, low_memory=False, **kwargs)
        logger.info(f"    → {len(df):,} rows  ×  {len(df.columns)} columns")
        return df
    except Exception as exc:
        logger.error(f"  ✘ Failed to load {name}: {exc}")
        return pd.DataFrame()


def clean_text(series: pd.Series) -> pd.Series:
    """
    Basic text normalisation: lower case, strip whitespace, replace NaN.

    Parameters
    ----------
    series : pd.Series of raw text.

    Returns
    -------
    pd.Series of cleaned text strings.
    """
    return (
        series.fillna("")
        .astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 1 — INGREDIENT SIMILARITY (TF-IDF + COSINE)
# ─────────────────────────────────────────────────────────────────────────────

def train_ingredient_similarity(df: pd.DataFrame) -> dict:
    """
    Build a TF-IDF vectorizer over ingredient text and compute the full
    cosine-similarity matrix.  Also exports a product_id → index mapping.

    Parameters
    ----------
    df : master_cleaned DataFrame. Must contain columns:
         'product_id', 'product_name', and either 'ingredients' or
         'ingredients_clean'.

    Returns
    -------
    dict with keys 'vectorizer', 'sim_matrix', 'product_ids', 'metrics'.
    """
    log_section("MODEL 1 — Ingredient Similarity (TF-IDF + Cosine)")
    t0 = time.time()

    # ── choose best ingredient column
    ing_col = "ingredients_clean" if "ingredients_clean" in df.columns else "ingredients"
    logger.info(f"  Using ingredient column: '{ing_col}'")

    subset = df[["product_id", "product_name", ing_col]].drop_duplicates(
        subset="product_id"
    )
    subset = subset.dropna(subset=["product_id"])

    # Clean text
    subset = subset.copy()
    subset["ing_text"] = clean_text(subset[ing_col])

    # Drop rows with empty ingredient text
    non_empty = subset[subset["ing_text"].str.len() > 2]
    logger.info(
        f"  Products with ingredient text: {len(non_empty):,} / {len(subset):,}"
    )

    if len(non_empty) < 10:
        logger.warning(
            "  Very few products with ingredient data — similarity matrix may be sparse."
        )

    # Build TF-IDF
    vectorizer = TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        sublinear_tf=True,
        min_df=2,
    )
    tfidf_matrix = vectorizer.fit_transform(non_empty["ing_text"])
    logger.info(
        f"  TF-IDF matrix shape: {tfidf_matrix.shape[0]:,} docs × {tfidf_matrix.shape[1]:,} features"
    )

    # Compute cosine similarity
    logger.info("  Computing cosine similarity matrix …")
    sim_matrix = cosine_similarity(tfidf_matrix, dense_output=False)
    logger.info(f"  Similarity matrix: {sim_matrix.shape}")

    product_ids = list(non_empty["product_id"].values)
    product_names = list(non_empty["product_name"].values)

    # ── save artefacts
    save_model(vectorizer,  "tfidf_vectorizer.pkl",        "TF-IDF Vectorizer")
    save_model(sim_matrix,  "cosine_similarity_matrix.pkl","Cosine Similarity Matrix")
    save_model(
        {"product_ids": product_ids, "product_names": product_names},
        "product_id_index.pkl",
        "Product ID → Index Mapping",
    )

    # ── sample evaluation: top-5 similar for first product
    metrics = {}
    if len(product_ids) > 5:
        sample_idx = 0
        sims = sim_matrix[sample_idx].toarray().flatten()
        top_idx = np.argsort(sims)[::-1][1:6]
        sample_product = product_names[sample_idx]
        logger.info(f"\n  Sample — top-5 similar to '{sample_product}':")
        for i, idx in enumerate(top_idx, 1):
            logger.info(
                f"    {i}. {product_names[idx]:<50s}  score={sims[idx]:.4f}"
            )
        metrics["sample_product"] = sample_product
        metrics["top_5_similar"] = [
            {"name": product_names[idx], "score": round(float(sims[idx]), 4)}
            for idx in top_idx
        ]

    metrics["n_products"]  = len(product_ids)
    metrics["n_features"]  = tfidf_matrix.shape[1]
    metrics["elapsed"]     = elapsed(t0)
    logger.info(f"\n  ✔ Ingredient Similarity complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 2 — HARMFUL INGREDIENT DETECTOR
# ─────────────────────────────────────────────────────────────────────────────

def compute_safety_score(ingredient_text: str) -> Tuple[float, List[dict]]:
    """
    Compute a safety score (0–100) for a product based on its ingredient list.
    100 = perfectly safe (no known harmful ingredients detected).

    Parameters
    ----------
    ingredient_text : Raw ingredient string for one product.

    Returns
    -------
    (safety_score, list_of_detected_harmful_ingredients)
    """
    if not ingredient_text or str(ingredient_text).lower() in ("nan", ""):
        return 100.0, []

    text = str(ingredient_text).lower()
    found: List[dict] = []
    total_severity = 0

    for keyword, info in HARMFUL_KEYWORDS.items():
        if keyword in text:
            found.append(
                {
                    "keyword":  keyword,
                    "name":     info["name"],
                    "reason":   info["reason"],
                    "severity": info["severity"],
                }
            )
            total_severity += info["severity"]

    # Cap deduction: max penalty = 100, each severity point = 4 points deducted
    penalty = min(total_severity * 4, 100)
    score = max(0.0, 100.0 - penalty)
    return round(score, 1), found


def train_harmful_detector(df: pd.DataFrame) -> dict:
    """
    Build and export the rule-based harmful ingredient detector engine.
    Computes safety scores for each product and saves the engine config.

    Parameters
    ----------
    df : master_cleaned DataFrame (or reviews DataFrame).

    Returns
    -------
    dict with evaluation metrics.
    """
    log_section("MODEL 2 — Harmful Ingredient Detector (Rule-Based)")
    t0 = time.time()

    # Prefer the reviews ingredients column (more complete)
    ing_col = None
    for col in ["ingredients", "ingredients_clean", "ingridients"]:
        if col in df.columns:
            ing_col = col
            break

    if ing_col is None:
        logger.warning("  No ingredient column found — skipping mock detector export.")
        detector_payload = {
            "harmful_keywords": HARMFUL_KEYWORDS,
            "scoring_fn": "compute_safety_score",
            "note": "No ingredient column found in dataset",
        }
        save_model(detector_payload, "harmful_detector.pkl", "Harmful Detector Engine")
        return {}

    logger.info(f"  Using ingredient column: '{ing_col}'")

    pid_col = "product_id" if "product_id" in df.columns else None
    if pid_col:
        subset = df[[pid_col, ing_col]].drop_duplicates(subset=pid_col).copy()
    else:
        subset = df[[ing_col]].copy()

    total = len(subset)
    logger.info(f"  Scoring {total:,} products …")

    results = subset[ing_col].apply(
        lambda x: pd.Series(compute_safety_score(str(x)), index=["safety_score", "harmful_found"])
    )
    subset = pd.concat([subset.reset_index(drop=True), results], axis=1)

    n_safe       = int((subset["safety_score"] >= 80).sum())
    n_unsafe     = int((subset["safety_score"] <  50).sum())
    n_moderate   = total - n_safe - n_unsafe
    mean_score   = round(float(subset["safety_score"].mean()), 2)

    logger.info(f"  Mean safety score : {mean_score}")
    logger.info(f"  Safe   (≥80)      : {n_safe:,}  ({100*n_safe/total:.1f}%)")
    logger.info(f"  Moderate (50–79)  : {n_moderate:,}  ({100*n_moderate/total:.1f}%)")
    logger.info(f"  Unsafe (<50)      : {n_unsafe:,}  ({100*n_unsafe/total:.1f}%)")

    # Most common harmful ingredients across dataset
    all_found: List[str] = []
    for row in subset["harmful_found"]:
        if isinstance(row, list):
            all_found.extend([i["name"] for i in row])

    from collections import Counter
    top_harmful = Counter(all_found).most_common(10)
    if top_harmful:
        logger.info("\n  Top-10 most common harmful ingredients:")
        for name, count in top_harmful:
            logger.info(f"    {count:5,}×  {name}")

    # Save the engine (config + keyword dict + statistics)
    detector_payload = {
        "harmful_keywords":   HARMFUL_KEYWORDS,
        "scoring_fn":         "compute_safety_score",
        "stats": {
            "n_products":     total,
            "mean_safety":    mean_score,
            "n_safe":         n_safe,
            "n_moderate":     n_moderate,
            "n_unsafe":       n_unsafe,
            "top_harmful":    top_harmful,
        },
    }
    save_model(detector_payload, "harmful_detector.pkl", "Harmful Detector Engine")

    metrics = {
        "n_products":   total,
        "mean_safety":  mean_score,
        "n_safe":       n_safe,
        "n_moderate":   n_moderate,
        "n_unsafe":     n_unsafe,
        "elapsed":      elapsed(t0),
    }
    logger.info(f"\n  ✔ Harmful Detector complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 3 — SKIN-TYPE CLASSIFICATION
# ─────────────────────────────────────────────────────────────────────────────

def train_skin_classifier(df_master: pd.DataFrame, df_reviews: pd.DataFrame) -> dict:
    """
    Train a text-based skin-type classifier using review text and
    the skin_suitability labels from the master dataset.

    Pipeline: TF-IDF → LogisticRegression (multi-class)

    Parameters
    ----------
    df_master  : master_cleaned DataFrame with 'skin_suitability'.
    df_reviews : master_reviews DataFrame with 'review_text' and 'product_id'.

    Returns
    -------
    dict with accuracy, F1 and classification report.
    """
    log_section("MODEL 3 — Skin-Type Classifier (TF-IDF + LogisticRegression)")
    t0 = time.time()

    # ── build training data: join review_text with skin_suitability label
    reviews_needed = ["product_id", "review_text"]
    master_needed  = ["product_id", "skin_suitability"]

    missing_r = [c for c in reviews_needed if c not in df_reviews.columns]
    missing_m = [c for c in master_needed  if c not in df_master.columns]

    if missing_r or missing_m:
        logger.warning(f"  Missing columns — reviews: {missing_r}, master: {missing_m}")
        logger.warning("  Attempting fallback with available columns …")

    # Merge skin label onto reviews
    skin_labels = df_master[["product_id", "skin_suitability"]].drop_duplicates()
    review_sub  = df_reviews[["product_id", "review_text"]].dropna(subset=["review_text"])

    merged = review_sub.merge(skin_labels, on="product_id", how="inner")
    merged = merged.dropna(subset=["skin_suitability", "review_text"])
    merged["skin_suitability"] = merged["skin_suitability"].str.strip().str.lower()

    # Keep only classes with sufficient samples
    class_counts = merged["skin_suitability"].value_counts()
    valid_classes = class_counts[class_counts >= 5].index
    merged = merged[merged["skin_suitability"].isin(valid_classes)]

    logger.info(f"  Training samples after filter: {len(merged):,}")
    logger.info(f"  Classes: {list(sorted(merged['skin_suitability'].unique()))}")

    if len(merged) < 20:
        logger.warning("  Insufficient labelled data for skin classifier — saving placeholder.")
        skin_pipeline = Pipeline([
            ("tfidf", TfidfVectorizer(max_features=3000)),
            ("clf",   LogisticRegression(max_iter=500, C=1.0)),
        ])
        save_model(skin_pipeline, "skin_model.pkl", "Skin-Type Classifier (unfitted)")
        return {"note": "insufficient data", "elapsed": elapsed(t0)}

    X = clean_text(merged["review_text"]).values
    y = merged["skin_suitability"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    logger.info(f"  Train/Test split: {len(X_train):,} / {len(X_test):,}")

    # Build and train the pipeline
    skin_pipeline = Pipeline([
        (
            "tfidf",
            TfidfVectorizer(
                max_features=10000,
                ngram_range=(1, 2),
                sublinear_tf=True,
                min_df=2,
            ),
        ),
        (
            "clf",
            LogisticRegression(
                max_iter=1000,
                C=1.0,
                class_weight="balanced",
                solver="lbfgs",
                multi_class="auto",
            ),
        ),
    ])

    logger.info("  Fitting Skin-Type Pipeline …")
    skin_pipeline.fit(X_train, y_train)

    # Evaluate
    y_pred = skin_pipeline.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)
    f1_w   = f1_score(y_test, y_pred, average="weighted", zero_division=0)
    f1_m   = f1_score(y_test, y_pred, average="macro",    zero_division=0)
    report = classification_report(y_test, y_pred, zero_division=0)

    logger.info(f"\n  ── Skin Classifier Evaluation ──")
    logger.info(f"  Accuracy (Test) : {acc:.4f}  ({acc*100:.2f}%)")
    logger.info(f"  F1 (Weighted)   : {f1_w:.4f}")
    logger.info(f"  F1 (Macro)      : {f1_m:.4f}")
    logger.info(f"\n  Classification Report:\n{report}")

    save_model(skin_pipeline, "skin_model.pkl", "Skin-Type Classifier")

    metrics = {
        "accuracy":    round(float(acc), 4),
        "f1_weighted": round(float(f1_w), 4),
        "f1_macro":    round(float(f1_m), 4),
        "n_classes":   int(len(valid_classes)),
        "n_train":     len(X_train),
        "n_test":      len(X_test),
        "elapsed":     elapsed(t0),
    }
    logger.info(f"\n  ✔ Skin Classifier complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 4 — SENTIMENT ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────

def _has_sentiment_labels(df_reviews: pd.DataFrame) -> Tuple[bool, Optional[str]]:
    """
    Check whether the reviews DataFrame contains usable sentiment labels.

    Returns
    -------
    (True, column_name)  if explicit sentiment column found,
    (False, None)        otherwise.
    """
    # Only columns whose values actually look like sentiment labels
    SENTIMENT_VALUES = {"positive", "negative", "neutral", "pos", "neg", "neu",
                        "good", "bad", "5", "4", "3", "2", "1"}
    candidates = ["sentiment", "sentiment_label", "review_sentiment"]
    for col in candidates:
        if col in df_reviews.columns:
            vals = set(str(v).strip().lower() for v in df_reviews[col].dropna().unique())
            if len(vals) >= 2 and vals.issubset(SENTIMENT_VALUES | {"mixed", "very positive", "very negative"}):
                logger.info(f"  Found sentiment label column: '{col}' ({len(vals)} unique values)")
                return True, col
    # Check 'label' only if its values overlap with sentiment vocabulary
    if "label" in df_reviews.columns:
        vals = set(str(v).strip().lower() for v in df_reviews["label"].dropna().unique())
        if vals.issubset(SENTIMENT_VALUES | {"mixed"}):
            logger.info("  Found sentiment labels in 'label' column.")
            return True, "label"
    logger.info("  No true sentiment label column found — will use VADER.")
    return False, None


def _vader_label(compound: float) -> str:
    """Convert a VADER compound score to a sentiment string."""
    if compound >= 0.05:
        return "positive"
    elif compound <= -0.05:
        return "negative"
    return "neutral"


def train_sentiment_model(df_reviews: pd.DataFrame) -> dict:
    """
    Train or build the sentiment analysis model.

    Strategy:
    - If explicit sentiment labels exist → TF-IDF + LogisticRegression classifier.
    - Otherwise                          → VADER rule-based analyser (SentimentIntensityAnalyzer).

    Parameters
    ----------
    df_reviews : master_reviews DataFrame containing 'review_text' + optional labels.

    Returns
    -------
    dict with evaluation metrics.
    """
    log_section("MODEL 4 — Sentiment Analysis")
    t0 = time.time()

    has_labels, label_col = _has_sentiment_labels(df_reviews)

    # ── Branch A: Supervised classifier ──────────────────────────────────────
    if has_labels:
        logger.info("  ► Mode: Supervised Classifier (TF-IDF + LogisticRegression)")

        subset = df_reviews[["review_text", label_col]].dropna()
        subset = subset[subset["review_text"].str.strip().str.len() > 5]

        lbl_counts = subset[label_col].value_counts()
        valid_lbls = lbl_counts[lbl_counts >= 5].index
        subset = subset[subset[label_col].isin(valid_lbls)]

        logger.info(f"  Samples: {len(subset):,}  Classes: {list(valid_lbls)}")

        X = clean_text(subset["review_text"]).values
        y = subset[label_col].astype(str).values

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        sent_pipeline = Pipeline([
            ("tfidf", TfidfVectorizer(max_features=8000, ngram_range=(1, 2), sublinear_tf=True)),
            ("clf",   LogisticRegression(max_iter=1000, C=1.0, class_weight="balanced")),
        ])
        sent_pipeline.fit(X_train, y_train)

        y_pred = sent_pipeline.predict(X_test)
        acc    = accuracy_score(y_test, y_pred)
        f1_w   = f1_score(y_test, y_pred, average="weighted", zero_division=0)
        report = classification_report(y_test, y_pred, zero_division=0)

        logger.info(f"\n  ── Sentiment Classifier Evaluation ──")
        logger.info(f"  Accuracy   : {acc:.4f}  ({acc*100:.2f}%)")
        logger.info(f"  F1 (Weighted): {f1_w:.4f}")
        logger.info(f"\n  Classification Report:\n{report}")

        model_payload = {
            "mode":     "classifier",
            "pipeline": sent_pipeline,
        }
        save_model(model_payload, "sentiment_model.pkl", "Sentiment Classifier")

        metrics = {
            "mode":        "classifier",
            "accuracy":    round(float(acc), 4),
            "f1_weighted": round(float(f1_w), 4),
            "elapsed":     elapsed(t0),
        }

    # ── Branch B: VADER Rule-Based ────────────────────────────────────────────
    else:
        logger.info("  ► Mode: Rule-Based VADER (no sentiment labels detected)")
        try:
            from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
        except ImportError:
            logger.warning("  vaderSentiment not installed — falling back to TextBlob")
            try:
                from textblob import TextBlob
                model_payload = {"mode": "textblob", "analyzer": "TextBlob"}
                save_model(model_payload, "sentiment_model.pkl", "Sentiment (TextBlob)")
                metrics = {"mode": "textblob", "elapsed": elapsed(t0)}
                logger.info(f"\n  ✔ Sentiment (TextBlob) complete  ({elapsed(t0)})")
                return metrics
            except ImportError:
                logger.error("  Neither VADER nor TextBlob available — sentiment model skipped.")
                return {"mode": "none", "elapsed": elapsed(t0)}

        analyzer = SentimentIntensityAnalyzer()

        # Score a sample to derive distribution
        sample = df_reviews["review_text"].dropna().head(5000)
        scores = sample.apply(
            lambda x: _vader_label(analyzer.polarity_scores(str(x))["compound"])
        )
        dist = scores.value_counts(normalize=True).round(3).to_dict()

        logger.info(f"  VADER distribution (sample of {len(sample):,}): {dist}")

        # Validate with rating if available
        if "rating_value" in df_reviews.columns:
            ratings = df_reviews[["review_text", "rating_value"]].dropna()
            ratings = ratings[ratings["review_text"].str.len() > 5].head(3000)
            ratings["vader_sentiment"] = ratings["review_text"].apply(
                lambda x: _vader_label(analyzer.polarity_scores(str(x))["compound"])
            )
            # Treat rating ≥ 4 as positive, ≤ 2 as negative, else neutral
            ratings["true_sentiment"] = ratings["rating_value"].apply(
                lambda r: "positive" if r >= 4 else ("negative" if r <= 2 else "neutral")
            )
            acc_proxy = (ratings["vader_sentiment"] == ratings["true_sentiment"]).mean()
            logger.info(f"  VADER vs rating proxy accuracy: {acc_proxy:.4f}  ({acc_proxy*100:.2f}%)")
            metrics = {
                "mode":          "vader",
                "proxy_accuracy": round(float(acc_proxy), 4),
                "distribution":   dist,
                "elapsed":        elapsed(t0),
            }
        else:
            logger.info("  No rating column found — skipping proxy accuracy.")
            metrics = {
                "mode":         "vader",
                "distribution": dist,
                "elapsed":      elapsed(t0),
            }

        model_payload = {
            "mode":     "vader",
            "analyzer": analyzer,
            "distribution": dist,
        }
        save_model(model_payload, "sentiment_model.pkl", "Sentiment Model (VADER)")

    logger.info(f"\n  ✔ Sentiment Analysis complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 5A — ARIMA DEMAND FORECASTING
# ─────────────────────────────────────────────────────────────────────────────

def _make_sales_ts(df_sales: pd.DataFrame, freq: str = "W") -> pd.DataFrame:
    """
    Aggregate sales data into a time series at the given frequency.
    Returns a DataFrame with DatetimeIndex and per-product columns.

    Parameters
    ----------
    df_sales : master_sales DataFrame.
    freq     : Pandas offset alias ('W' = weekly, 'D' = daily, 'M' = monthly).

    Returns
    -------
    pd.DataFrame  — wide format: rows = dates, columns = product_id.
    """
    # Detect date column
    date_col = None
    for col in ["start_date", "order_date", "date", "date_published"]:
        if col in df_sales.columns:
            date_col = col
            break

    qty_col = None
    for col in ["units_sold", "sales", "venda", "revenues"]:
        if col in df_sales.columns:
            qty_col = col
            break

    pid_col = "product_id" if "product_id" in df_sales.columns else None

    if date_col is None or qty_col is None:
        logger.warning("  Could not identify date or quantity column in sales data.")
        return pd.DataFrame()

    sub = df_sales[[date_col, pid_col, qty_col]].copy() if pid_col else df_sales[[date_col, qty_col]].copy()
    sub[date_col] = pd.to_datetime(sub[date_col], errors="coerce")
    sub[qty_col]  = pd.to_numeric(sub[qty_col], errors="coerce")
    sub = sub.dropna(subset=[date_col, qty_col])
    sub = sub[sub[qty_col] >= 0]

    if pid_col:
        ts = (
            sub.groupby([pd.Grouper(key=date_col, freq=freq), pid_col])[qty_col]
            .sum()
            .unstack(fill_value=0)
        )
    else:
        ts = sub.groupby(pd.Grouper(key=date_col, freq=freq))[qty_col].sum().to_frame()

    return ts.sort_index()


def train_arima(df_sales: pd.DataFrame, top_n: int = 5) -> dict:
    """
    Fit ARIMA models for the top-N products by total sales.

    Parameters
    ----------
    df_sales : master_sales DataFrame.
    top_n    : Number of top products to fit ARIMA for.

    Returns
    -------
    dict with RMSE, MAE per product and combined metrics.
    """
    log_section("MODEL 5A — ARIMA Demand Forecasting")
    t0 = time.time()

    try:
        from statsmodels.tsa.arima.model import ARIMA
    except ImportError:
        logger.error("  statsmodels not installed — ARIMA skipped.")
        return {"error": "statsmodels missing"}

    ts = _make_sales_ts(df_sales, freq="W")
    if ts.empty:
        logger.warning("  Could not build time series — ARIMA skipped.")
        save_model({"error": "no time series"}, "arima_model.pkl", "ARIMA Model (empty)")
        return {}

    # Select top-N products
    if isinstance(ts.columns, pd.MultiIndex) or ts.shape[1] > 1:
        top_products = ts.sum().nlargest(top_n).index.tolist()
    else:
        top_products = ts.columns.tolist()

    logger.info(f"  Time series shape : {ts.shape}")
    logger.info(f"  Date range        : {ts.index.min()} → {ts.index.max()}")
    logger.info(f"  Fitting ARIMA for top-{len(top_products)} products …")

    arima_models: dict = {}
    all_rmse: List[float] = []
    all_mae:  List[float] = []

    for pid in top_products:
        try:
            product_ts = ts[pid].dropna()
            if len(product_ts) < 12:
                logger.warning(f"    {pid}: too few observations ({len(product_ts)}) — skipping")
                continue

            # Simple train/test split
            split = max(4, int(len(product_ts) * 0.8))
            train_ts = product_ts.iloc[:split]
            test_ts  = product_ts.iloc[split:]

            model = ARIMA(train_ts, order=(1, 1, 1))
            fitted = model.fit()

            if len(test_ts) > 0:
                forecasts = fitted.forecast(steps=len(test_ts))
                rmse = float(np.sqrt(mean_squared_error(test_ts, forecasts)))
                mae  = float(np.mean(np.abs(test_ts.values - forecasts.values)))
                all_rmse.append(rmse)
                all_mae.append(mae)
                logger.info(f"    {str(pid)[:20]:20s}  RMSE={rmse:8.2f}  MAE={mae:8.2f}  n={len(product_ts)}")
            else:
                logger.info(f"    {str(pid)[:20]:20s}  n={len(product_ts)} (no test split)")

            arima_models[str(pid)] = fitted
        except Exception as exc:
            logger.warning(f"    {pid}: ARIMA failed — {exc}")

    mean_rmse = float(np.mean(all_rmse)) if all_rmse else None
    mean_mae  = float(np.mean(all_mae))  if all_mae  else None

    logger.info(f"\n  ── ARIMA Summary ({len(arima_models)} models) ──")
    if mean_rmse:
        logger.info(f"  Mean RMSE : {mean_rmse:.2f}")
        logger.info(f"  Mean MAE  : {mean_mae:.2f}")

    save_model(
        {"models": arima_models, "top_products": [str(p) for p in top_products]},
        "arima_model.pkl",
        "ARIMA Demand Forecast Models",
    )

    metrics = {
        "n_products":  len(arima_models),
        "mean_rmse":   round(mean_rmse, 4) if mean_rmse else None,
        "mean_mae":    round(mean_mae, 4)  if mean_mae  else None,
        "elapsed":     elapsed(t0),
    }
    logger.info(f"\n  ✔ ARIMA complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# MODEL 5B — RANDOM FOREST DEMAND FORECASTING
# ─────────────────────────────────────────────────────────────────────────────

def _engineer_forecast_features(ts_series: pd.Series) -> pd.DataFrame:
    """
    Engineer time-series features for a univariate sales series.

    Features created:
      - month, week_of_year, quarter  (from index)
      - lag_1, lag_2, lag_4, lag_8    (lagged values)
      - rolling_mean_4                 (4-week rolling mean)
      - season                         (1–4 per quarter)
      - is_holiday_season              (flag for Q4)

    Parameters
    ----------
    ts_series : pd.Series with DatetimeIndex and numeric values.

    Returns
    -------
    pd.DataFrame of features with target column 'y'.
    """
    df = pd.DataFrame({"y": ts_series})
    df["month"]           = df.index.month
    df["week_of_year"]    = df.index.isocalendar().week.astype(int)
    df["quarter"]         = df.index.quarter
    df["season"]          = (df["quarter"] - 1) % 4 + 1
    df["is_holiday"]      = (df["quarter"] == 4).astype(int)
    df["lag_1"]           = df["y"].shift(1)
    df["lag_2"]           = df["y"].shift(2)
    df["lag_4"]           = df["y"].shift(4)
    df["lag_8"]           = df["y"].shift(8)
    df["rolling_mean_4"]  = df["y"].shift(1).rolling(4).mean()
    return df.dropna()


def train_rf_forecast(df_sales: pd.DataFrame) -> dict:
    """
    Train a global RandomForestRegressor for demand forecasting.
    Uses feature-engineered time-series data across all products.

    Parameters
    ----------
    df_sales : master_sales DataFrame.

    Returns
    -------
    dict with RMSE, MAE, R² metrics.
    """
    log_section("MODEL 5B — Random Forest Demand Forecasting")
    t0 = time.time()

    ts = _make_sales_ts(df_sales, freq="W")
    if ts.empty:
        logger.warning("  Time series is empty — RF Forecast skipped.")
        save_model(None, "rf_forecast_model.pkl", "RF Forecast (empty)")
        return {}

    # Build global feature table across all product columns
    frames: List[pd.DataFrame] = []

    cols = ts.columns if ts.shape[1] > 1 else ts.columns
    for col in cols:
        feats = _engineer_forecast_features(ts[col])
        frames.append(feats)

    if not frames:
        logger.warning("  No engineered feature frames — RF Forecast skipped.")
        return {}

    combined = pd.concat(frames, ignore_index=True)
    combined = combined.replace([np.inf, -np.inf], np.nan).dropna()

    feature_cols = [c for c in combined.columns if c != "y"]
    X = combined[feature_cols].values
    y = combined["y"].values

    # Train/Test split (chronological)
    split = int(len(combined) * 0.8)
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]

    logger.info(f"  Feature matrix : {combined.shape[0]:,} rows × {len(feature_cols)} features")
    logger.info(f"  Train/Test     : {len(X_train):,} / {len(X_test):,}")
    logger.info(f"  Features       : {feature_cols}")

    rf = RandomForestRegressor(
        n_estimators=200,
        max_depth=12,
        min_samples_split=5,
        min_samples_leaf=3,
        max_features="sqrt",
        n_jobs=-1,
        random_state=42,
    )
    logger.info("  Fitting Random Forest …")
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_test)
    rmse   = float(np.sqrt(mean_squared_error(y_test, y_pred)))
    mae    = float(np.mean(np.abs(y_test - y_pred)))
    r2     = float(r2_score(y_test, y_pred))

    logger.info(f"\n  ── RF Forecast Evaluation ──")
    logger.info(f"  RMSE  : {rmse:.4f}")
    logger.info(f"  MAE   : {mae:.4f}")
    logger.info(f"  R²    : {r2:.4f}")

    # Feature importances
    importances = sorted(
        zip(feature_cols, rf.feature_importances_),
        key=lambda x: x[1],
        reverse=True,
    )
    logger.info("\n  Feature Importances:")
    for fname, imp in importances:
        bar = "█" * int(imp * 40)
        logger.info(f"    {fname:<20s}  {imp:.4f}  {bar}")

    save_model(
        {"model": rf, "feature_cols": feature_cols},
        "rf_forecast_model.pkl",
        "Random Forest Demand Forecast",
    )

    metrics = {
        "rmse":           round(rmse, 4),
        "mae":            round(mae, 4),
        "r2":             round(r2, 4),
        "n_features":     len(feature_cols),
        "n_estimators":   rf.n_estimators,
        "elapsed":        elapsed(t0),
    }
    logger.info(f"\n  ✔ RF Forecast complete  ({elapsed(t0)})")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# INFERENCE HELPER FUNCTIONS (usable in backend routes)
# ─────────────────────────────────────────────────────────────────────────────

def get_similar_products(product_id: str, top_n: int = 5) -> list[dict]:
    """
    Backend inference helper — retrieve top-N similar products by TF-IDF cosine.

    Parameters
    ----------
    product_id : Target product identifier.
    top_n      : Number of similar products to return.

    Returns
    -------
    List of dicts: [{'product_id': ..., 'product_name': ..., 'similarity': ...}]
    """
    try:
        sim_matrix  = pickle.load(open(MODELS_DIR / "cosine_similarity_matrix.pkl", "rb"))
        id_map      = pickle.load(open(MODELS_DIR / "product_id_index.pkl", "rb"))
        product_ids = id_map["product_ids"]
        names_map   = {pid: name for pid, name in zip(id_map["product_ids"], id_map["product_names"])}

        if product_id not in product_ids:
            return []

        idx  = product_ids.index(product_id)
        sims = sim_matrix[idx].toarray().flatten()
        top  = np.argsort(sims)[::-1][1 : top_n + 1]

        return [
            {
                "product_id":   product_ids[i],
                "product_name": names_map.get(product_ids[i], ""),
                "similarity":   round(float(sims[i]), 4),
            }
            for i in top
        ]
    except Exception as exc:
        logger.warning(f"  get_similar_products error: {exc}")
        return []


def predict_safety(ingredient_text: str) -> dict:
    """
    Backend inference helper — compute safety score for an ingredient string.

    Parameters
    ----------
    ingredient_text : Raw ingredient list string.

    Returns
    -------
    dict: {'safety_score': float, 'status': str, 'harmful_ingredients': list}
    """
    score, found = compute_safety_score(ingredient_text)
    status = "Safe" if score >= 80 else ("Moderate" if score >= 50 else "Unsafe")
    return {
        "safety_score":        score,
        "status":              status,
        "harmful_ingredients": found,
    }


def predict_skin_type(review_text: str) -> dict:
    """
    Backend inference helper — predict skin type suitability from review text.

    Parameters
    ----------
    review_text : Review string.

    Returns
    -------
    dict: {'skin_type': str, 'probabilities': dict}
    """
    try:
        model = pickle.load(open(MODELS_DIR / "skin_model.pkl", "rb"))
        pred  = model.predict([review_text])[0]
        proba = model.predict_proba([review_text])[0]
        classes = model.classes_
        return {
            "skin_type":     pred,
            "probabilities": {c: round(float(p), 4) for c, p in zip(classes, proba)},
        }
    except Exception as exc:
        logger.warning(f"  predict_skin_type error: {exc}")
        return {"skin_type": "unknown", "probabilities": {}}


def predict_sentiment(review_text: str) -> dict:
    """
    Backend inference helper — analyse sentiment of a review string.

    Parameters
    ----------
    review_text : Review text.

    Returns
    -------
    dict: {'sentiment': str, 'compound': float, 'scores': dict}
    """
    try:
        payload = pickle.load(open(MODELS_DIR / "sentiment_model.pkl", "rb"))
        mode    = payload.get("mode", "vader")

        if mode == "classifier":
            pipeline = payload["pipeline"]
            label    = pipeline.predict([review_text])[0]
            proba    = pipeline.predict_proba([review_text])[0]
            return {
                "sentiment":  label,
                "mode":       "classifier",
                "confidence": round(float(max(proba)), 4),
            }
        elif mode == "vader":
            analyzer = payload["analyzer"]
            scores   = analyzer.polarity_scores(review_text)
            return {
                "sentiment": _vader_label(scores["compound"]),
                "compound":  round(scores["compound"], 4),
                "scores":    {k: round(v, 4) for k, v in scores.items()},
                "mode":      "vader",
            }
        else:
            from textblob import TextBlob
            blob = TextBlob(review_text)
            pol  = blob.sentiment.polarity
            return {
                "sentiment": "positive" if pol > 0.05 else ("negative" if pol < -0.05 else "neutral"),
                "polarity":  round(pol, 4),
                "mode":      "textblob",
            }
    except Exception as exc:
        logger.warning(f"  predict_sentiment error: {exc}")
        return {"sentiment": "unknown"}


# ─────────────────────────────────────────────────────────────────────────────
# METRICS REPORT
# ─────────────────────────────────────────────────────────────────────────────

def save_metrics_report(all_metrics: dict) -> None:
    """
    Persist all training metrics as a JSON report.

    Parameters
    ----------
    all_metrics : Dict keyed by model name → metrics dict.
    """
    report = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "models": all_metrics,
    }
    path = MODELS_DIR / "training_report.json"
    with open(path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    logger.info(f"  ✔ Training report saved → {path.name}")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

AVAILABLE_MODELS = ["similarity", "harmful", "skin", "sentiment", "forecast"]


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Train all ML models for the Cosmetic Market Intelligence System."
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=["all"],
        choices=AVAILABLE_MODELS + ["all"],
        help="Which models to train. Use 'all' to train everything.",
    )
    return parser.parse_args()


def main() -> None:
    """
    Orchestrate the full training pipeline.
    Loads all datasets once, then dispatches to each model training function.
    """
    args = parse_args()
    train_all  = "all" in args.models
    to_train   = AVAILABLE_MODELS if train_all else args.models

    log_section("COSMETIC MARKET INTELLIGENCE — ML TRAINING PIPELINE")
    logger.info(f"  Start time   : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info(f"  Models       : {to_train}")
    logger.info(f"  Output dir   : {MODELS_DIR}")
    logger.info(f"  Data dir     : {DATA_DIR}")
    pipeline_start = time.time()

    # ── Load datasets ──────────────────────────────────────────────────────
    log_section("DATA LOADING")
    df_master  = load_csv(DATA_MASTER,  "master_cleaned")
    df_sales   = load_csv(DATA_SALES,   "master_sales_cleaned")
    df_reviews = load_csv(DATA_REVIEWS, "master_reviews_cleaned")

    all_metrics: dict = {}

    # ── Model 1: Ingredient Similarity ────────────────────────────────────
    if "similarity" in to_train:
        # Prefer master_ingredients if available
        ing_path = DATA_DIR / "master_ingredients_cleaned.csv"
        if ing_path.exists():
            df_ing = load_csv(ing_path, "master_ingredients_cleaned")
            # Merge into master if product_id present
            if "product_id" in df_ing.columns and "product_id" in df_master.columns:
                df_for_sim = df_master.copy()
                if "ingredients" not in df_for_sim.columns or df_for_sim["ingredients"].isna().mean() > 0.5:
                    logger.info("  Merging ingredients from master_ingredients_cleaned …")
                    df_for_sim = df_master.merge(
                        df_ing[["product_id", "ingredients"]].dropna(),
                        on="product_id",
                        how="left",
                        suffixes=("_old", ""),
                    )
            else:
                df_for_sim = df_master
        else:
            df_for_sim = df_master

        all_metrics["similarity"] = train_ingredient_similarity(df_for_sim)

    # ── Model 2: Harmful Detector ─────────────────────────────────────────
    if "harmful" in to_train:
        # Use reviews df (richer ingredient data) if available
        df_for_harm = df_reviews if not df_reviews.empty else df_master
        all_metrics["harmful"] = train_harmful_detector(df_for_harm)

    # ── Model 3: Skin Classifier ──────────────────────────────────────────
    if "skin" in to_train:
        all_metrics["skin"] = train_skin_classifier(df_master, df_reviews)

    # ── Model 4: Sentiment Analysis ───────────────────────────────────────
    if "sentiment" in to_train:
        all_metrics["sentiment"] = train_sentiment_model(df_reviews)

    # ── Model 5: Demand Forecasting ───────────────────────────────────────
    if "forecast" in to_train:
        all_metrics["arima"]    = train_arima(df_sales, top_n=5)
        all_metrics["rf_forecast"] = train_rf_forecast(df_sales)

    # ── Save overall report ───────────────────────────────────────────────
    log_section("TRAINING COMPLETE — SUMMARY")
    save_metrics_report(all_metrics)
    logger.info(f"\n  Total elapsed: {elapsed(pipeline_start)}")
    logger.info(f"  Models dir  : {MODELS_DIR}")
    logger.info(f"\n  Saved artefacts:")
    for f in sorted(MODELS_DIR.glob("*.pkl")):
        size_kb = f.stat().st_size / 1024
        logger.info(f"    {f.name:<40s}  {size_kb:8.1f} KB")

    logger.info("\n  ✅ All models trained successfully.")


if __name__ == "__main__":
    main()
